{{- range .Values.services }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # если нужен Linkerd, убеждаемся что ingress-controller уже инжектирован!
spec:
  rules:
    - host: {{ .host | default (printf "%s.local" .name) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .port }}
{{- end }}